### ISSUE TITLE
JWE set algorithm

### ISSUE THREAD

**Issue by R-Led** [cisco/node-jose#151]
I am trying to encrypt data using JWE.createEncrypt with a shared secret key ('key':'oct', 'alg':'dir') but I don't understand how to set the encryption algorithm. I would like to use 'A128CBC-HS256'.

**Comment by linuxwolf** [comment]
It's best to set the key's `alg` value to what you ultimately want to use it for.  In your case, it should be `A128CBC-HS256`:

```json
{
  "kty": "oct",
  "k": ...,
  "alg": "A128CBC-HS256"
}
```

If the key's `alg` is a content encryption algorithm (registered as an `enc` header parameter instead of as an `alg` header parameter), this library should do the right thing and use `"alg":"dir"` and `"enc":"A128CBC-HS256"`.

Otherwise, you can set the key encryption algorithm (`alg`) via a `fields` property:

```javascript
let jwe = jose.JWE.createEncrypt({
  fields: {
    alg: "dir",
    enc: "A128CBC-HS256"
  }
}, key);
```

**Comment by kentsitugbc** [comment]
Hi, @linuxwolf , currently I am also working on something like this. In the client I want to decrypt the encrypted token from back end. I am using "A128CBC-HS256" to decrypt also. I have the key, iv, authTag. Can you give me a full example how to achieve that because I don't really understand the process? By the way, Since I am using angular 4, I cannot use some nodejs module like crypto.
Thank you very much!

**Comment by linuxwolf** [comment]
@kentsitugbc are you saying you'd *don't* have a serialized JWE object, but the individual pieces (key, iv, ciphertext, authtag)?  A JWE object -- in any serialization -- should have everything minus the key contained within.

If you have the JWE object and the key, then you can do the following:
```javascript
// assumes the following:
// * {key_json} is a JWK of the symmetric key
// * {jwe} is the JWE object serialized as Compact/Flattened JSON/General JSON
jose.JWK.asKey(key_json).
        then((key) => jose.JWE.createDecrypt(key).decrypt(jwe)).
        then((results) => {
          // results is an object; {results.payload} is plaintext, as a Buffer
        });
```

However, if the encrypted token was not created as a JWE object in the first place, you are likley missing a key factor -- the authdata, which is computed from the JWE protected header.

**Comment by branfon1** [comment]
I am trying to implement the same functionality but in Angular, your help please

npm install node-jose

const jose = require('node-jose');
const b64u = require('base64url');

var $clave = '3ZZK5Q7CDQLV210642W7ZWXC6NB3IFQJ';

// create key.
jose.JWK.asKeyStore([
  {
    kid: $clave,
    kty: 'oct',
    k: b64u($clave)
  }
]).then(ks => {

  console.log('ks', ks)
  // sign it
  jose.JWS.createSign(
    {
      format: 'compact'
    },
    {
      key: ks.get($clave),
      header: {
        alg: "HS256"
      }
    }
  )
    .update(JSON.stringify({ ppp: 12, ddd: 3883 }))
    .final()
    .then(sjwt => {
      console.log(`sjwt = ${sjwt}`);
      // encrypt the signed message
      jose.JWE.createEncrypt(
        {
          format: 'compact'
        },
        {
          key: ks.get($clave),
          header: {
            alg: 'dir',
            enc: 'A128CBC-HS256'
          }
        }
      )
        .update(sjwt)
        .final()
        .then(ejwt => {
          console.log(`ejwt = ${ejwt}`);
          // decrypt the last message and failed in there.
          jose.JWE.createDecrypt(ks.get($clave))
            .decrypt(ejwt)
            .then(djwt => {
              console.log(JSON.stringify(djwt, null, '    '));
            });
        });
    });
});


expected result :
image

https://stackblitz.com/
