### ISSUE TITLE
How to encrypt with diffie helman algorithm.

### ISSUE THREAD

**Issue by endyjasmi** [cisco/node-jose#227]
Hello, may I know how do I encrypt a message using diffie helman algorithm with this library.

**Comment by panva** [comment]
Following the [encryption readme part](https://github.com/cisco/node-jose#encrypting-content) and putting the right [JWAs](https://tools.ietf.org/html/rfc7518) in.

e.g.
```js
const { JWE, JWK } = require('node-jose');

(async () => {
  // create a private EC key
  const priv = await JWK.createKey('EC', 'P-256');

  // simulate only having access to the public key, usually this is your starting point as you only have access to the public components if you're encrypting a message for someone else.
  const pub = await JWK.asKey(priv.toJSON());

  const encrypted = await JWE.createEncrypt({
    format: 'compact',
    fields: {
      alg: 'ECDH-ES',
      enc: 'A128CBC-HS256',
      cty: 'json', // replace with JWT if you're encrypting a JWT...
    },
  }, {
    key: pub,
  }).update(JSON.stringify({ foo: 'bar' })).final()

  console.log('encrypted', encrypted);


  // now we decrypt using the private key

  const decrypted = await JWE.createDecrypt(priv).decrypt(encrypted);
  console.log('decrypted', JSON.parse(decrypted.payload.toString('utf8')));
})().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
```

**Comment by endyjasmi** [comment]
What I am planning to do is to create an end to end encryption demo.

The basic idea is to generate key pair in 2 client where the public key is exchanged between each other.

The shared secret key is then generated with the combination of owner private key and recipient public key.

I am wondering how to achieve this with this library.

**Comment by phish108** [comment]
I fear that this is out of the immediate scope of the [JWA specification](https://tools.ietf.org/html/rfc7518) and JOSE as such.

[ECDH-ES](https://tools.ietf.org/html/rfc7518#section-4.6) assumes that one key pair is static (i.e., it never changes) and the other is short lived (i.e., single use). 

For your case I think that the [```dir``` (direct encryption)](https://tools.ietf.org/html/rfc7518#section-4.5) algorithm is most suitable once your parties agreed on a shared secret. In this case the content encryption key (```CEK```) is never included into the JWE your clients exchange between them, because this is the shared secret.

For that purpose you could store the shared secret at both ends as an ```oct``` key or compute it every time you need it (using the appropriate underlying crypto module). Your business logic is responsible that the clients use a reasonable ```kid``` for referring to the shared secret in the subsequent communication.

**Comment by panva** [comment]
alg and key negotiation between parties like one you described is out of scope for a JOSE implementation.
