### ISSUE TITLE
Getting unsupported algorithm when trying to encrypt my data

### ISSUE THREAD

**Issue by codemaster101** [cisco/node-jose#275]
Hi, I was trying to encrypt my data using node-jose

I created a key pair in the command line using 

`jose-util generate-key --use enc --alg ECDH-ES+A256KW`

Then I fed the contents of the public key into my environment variable.

I was encrypting my file like this

```
async function encrypt(data) {
	const pub = await jose.JWK.asKey(publicKey, 'json');
//	console.log(key);
	//const priv = await jose.JWK.createKey('EC', 'P-256');
	//const pub = await jose.JWK.asKey(priv.toJSON());
	const encrypted = await jose.JWE.createEncrypt(
      {
        format: 'general',
        fields: {
          alg: 'ECDH-ES',
          enc: 'A256GCM',
          cty: 'json',
        }
      },
      {
        key: pub
      },
    ).update(JSON.stringify(data))
    .final();

 console.log(encrypted);
}
```

When I run this code I get
Error: unsupported algorithm, but when I use the commented out code the code runs perfectly.

Is the key that I generated wrong? If so, how should I generate the keys?

**Comment by linuxwolf** [comment]
It looks like the key generated via `jose-util` is restricted to only the algorithm `ECDH-ES+A256KW`, but your code expects a key that is set to use `ECDH-ES` (note the lack of `+A256KW`).

The key you're generating in code works because it doesn't set any restrictions on use.  If you look at the contents of the generated key, you should see a field like:

```json
    "alg": "ECDH-ES+A256KW",
```
if you change that to `ECDH-ES` or remove it entirely, it should start working.  Alternatively, you can set your code to use `alg: "ECDH-ES+A256KW"` and it should also start working.
